language: go
sudo: false

go:
  - 1.7
  - 1.8  
  - 1.9
  - tip

install:
  - go get -t ./...

script: 
  - go test -short -v ./...
  - go build -v ./...
  - ./e2e.sh

# getting errors on https://github.com/goreleaser/goreleaser/blob/master/pipeline/release/release.go#L55
#after_success:
#  test -n "$TRAVIS_TAG" && go get github.com/goreleaser/goreleaser && goreleaser
